config/routes.rb
Rails.application.routes.draw do

  mount_devise_token_auth_for 'User', at: 'auth'
  match '/auth/confirm_registration', to: 'application#confirm_registration', via: :get

  resources :resumes do
    collection do
      get :resume_template_details
    end
  end
  resources :basic_info
  resources :contact_info
  resources :character_references
  resources :educations do
    member do
      get :attachments
      post :upload_attachment
      post :destroy_attachment
    end
  end
  resources :qualifications do
    member do
      get :attachments
      post :upload_attachment
      post :destroy_attachment
    end
  end
  resources :photos
  resources :skills
  resources :work_experiences do
    member do
      get :attachments
      post :upload_attachment
      post :destroy_attachment
    end
  end
  resources :newsletter_subscribers
  resources :previews do
    member do
      get :debug_params
      get :generate_css, as: 'generate_css'
      get :cover_letter
    end
  end
  resources :resume_configs do
    collection do
      get :fonts
    end
  end
  resources :dashboards
  resources :resume_page_setups
  resources :cover_letters
  resources :video_pitches

  resources :users do
    collection do
      get :myprofile
    end
  end

  root 'frontend/home#coming_soon'
  match 'homepage', to: 'frontend/home#index', via: :get, as: 'homepage'
  match 'login', to: 'frontend/home#auth', via: :get, as: 'login'
  match 'signup', to: 'frontend/home#signup', via: :get, as: 'signup'
  match 'auth/set_session', to: 'api#set_session', via: :post

end

app/controllers/frontend/home_controller.rb
class Frontend::HomeController < ApplicationController

	layout false

	def index
	end

	def coming_soon
	end

	def auth
		redirect_to dashboards_path unless cookies[:auth_headers].blank?
	end

	def signup
	end

end

app/views/frontend/home/auth.html.erb
<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
  <meta charset="utf-8"/>
  <title>Imprezify | Login Page</title>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
  <meta content="" name="description"/>
  <meta content="" name="author"/>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <link rel="icon" href="<%= image_path('frontend/favicon.ico') %>" type="image/x-icon" />
  <%= stylesheet_link_tag 'application' %>
</head>
<body class="pace-top" ng-app="authentication" ng-controller="SigninController"  style="height: auto">
<!-- begin #page-loader -->
<div id="page-loader" class="fade in"><span class="spinner"></span></div>
<!-- end #page-loader -->

<div class="login-cover">
  <div class="login-cover-image"><%= image_tag 'frontend/login-bg/bg-9.jpg', data: {id: 'login-cover-image'} %></div>
  <div class="login-cover-bg"></div>
</div>
<!-- begin #page-container -->
<div id="page-container" class="fade">
  <!-- begin login -->
  <div class="login login-v2" data-pageload-addclass="animated fadeIn">
    <div class="login-content">
      <div class="m-b-20 relative">
        <%= image_tag 'frontend/loginlogo.png', class: 'loginlogo' %>
        <strong class="absolute left-65 bottom--5">Get hired fast.</strong>
      </div>
      <form name="" class="margin-bottom-0" ng-submit="signin()">
        <div class="form-group m-b-20">
          <input type="text" class="form-control input-lg" name="email" ng-model="userForm.email" placeholder="Email Address"/>
        </div>
        <div class="form-group m-b-20">
          <input type="password" class="form-control input-lg" placeholder="Password" name="password" ng-model="userForm.password" />
        </div>
        <div class="checkbox m-b-20">
          <label>
            <input type="checkbox" name="remember_me" /> Remember Me
          </label>
        </div>
        <div class="login-buttons text-center">
          <button type="submit" class="btn btn-success btn-sm">Sign me in</button>
          <a class="btn btn-sm btn-social btn-linkedin" ng-click="signInWithLinkedin()">
            <span class="fa fa-linkedin"></span> Sign in with LinkedIn
          </a>
        </div>
        <div class="m-t-20">
          Not a member yet? Click <%= link_to 'here', signup_path %> to register.
        </div>
      </form>
    </div>
  </div>
  <!-- end login -->
</div>
<script>
    var BASE_API_URL = '<%= BASE_API_URL %>'
</script>
<%= javascript_include_tag 'auth' %>
<!--[if lt IE 9]>
<%= javascript_include_tag 'crossbrowser' %>
<![endif]-->

<script>
  $(document).ready(function () {
    App.init();
    LoginV2.init();
  });
</script>

<script>
    (function() {
        var interakt = document.createElement('script');
        interakt.type = 'text/javascript'; interakt.async = true;
        interakt.src = "//cdn.interakt.co/interakt/dd31c5ebd6b6f9fb20ad18b9777dd460.js";
        var scrpt = document.getElementsByTagName('script')[0];
        scrpt.parentNode.insertBefore(interakt, scrpt);
    })()
</script>
</body>
</html>

app/views/frontend/home/coming_soon.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <title>Imprezify | Coming Soon Page</title>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
  <meta content="Job searching application" name="description" />
  <meta content="Jonathan Canaveral" name="author" />
  <link rel="icon" href="<%= image_path('frontend/favicon.ico') %>" type="image/x-icon" />
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <%= stylesheet_link_tag 'coming-soon' %>
</head>
<body class="bg-white p-t-0 pace-top">
<!-- begin #page-loader -->
<div id="page-loader" class="fade in"><span class="spinner"></span></div>
<!-- end #page-loader -->
<!-- begin #page-container -->
<div id="page-container" class="fade">
  <!-- begin coming-soon -->
  <div class="coming-soon">
    <div class="coming-soon-header">
      <div class="bg-cover"></div>
      <div class="brand">
        <%= image_tag 'frontend/loginlogo.png', style: 'height: 60px; width: auto' %>
      </div>
      <div class="timer">
        <div id="timer"></div>
      </div>
      <div class="container" style="width: 600px;">
        <div class="desc text-left">
          <h4 class="text-white">What is Imprezify?</h4>
          <ul>
            <li>Imprezify is a CV generator app where user is able to generate professional looking CVs</li>
            <li>We will also provide you your personal showcase page where your employer can evaluate you and your application in detail.</li>
            <li>Your showcase page includes Infographic timelines and and video pitch.</li>
            <li>You can keep on track in your job application in real-time statistics and notification, you will know whoever views, download your CV or show interest in you.</li>
          </ul>
          <p>
            These key features will give you an advantage in the position you applying with.
          </p>
        </div>
      </div>
    </div>
    <div class="coming-soon-content">
      <div class="desc">
        We are launching a closed <b>beta</b> soon!<br /> Sign up now and be one of the first 100 users that can have FREE premium access to our services.
      </div>
      <div class="input-group">
        <%= link_to 'Sign Up NOW!', signup_path, class: 'btn btn-info m-b-10' %>
      </div>
      <p>
        Follow us on
        <a href="#"><i class="fa fa-twitter fa-fw"></i> Twitter</a> and
        <a href="#"><i class="fa fa-facebook fa-fw"></i> Facebook</a>
      </p>
    </div>
  </div>
  <!-- end coming-soon -->
</div>
<!-- end page container -->

<%= javascript_include_tag 'coming-soon' %>

<script>
    $(document).ready(function() {
        App.init();
        ComingSoon.init();
    });
</script>

<script>
    (function() {
        var interakt = document.createElement('script');
        interakt.type = 'text/javascript'; interakt.async = true;
        interakt.src = "//cdn.interakt.co/interakt/dd31c5ebd6b6f9fb20ad18b9777dd460.js";
        var scrpt = document.getElementsByTagName('script')[0];
        scrpt.parentNode.insertBefore(interakt, scrpt);
    })()
</script>
</body>
</html>

app/views/frontend/home/signup.html.erb
<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
  <meta charset="utf-8"/>
  <title>Imprezify | Sign up Page</title>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
  <meta content="" name="description"/>
  <meta content="" name="author"/>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <link rel="icon" href="<%= image_path('frontend/favicon.ico') %>" type="image/x-icon" />
  <%= stylesheet_link_tag 'application' %>
</head>
<body class="pace-top bg-white" ng-app="authentication" ng-controller="SignupController">
<!-- begin #page-loader -->
<div id="page-loader" class="fade in"><span class="spinner"></span></div>
<!-- end #page-loader -->

<!-- begin #page-container -->
<div id="page-container" class="fade">
  <!-- begin register -->
  <div class="register register-with-news-feed">
    <!-- begin news-feed -->
    <div class="news-feed">
      <div class="news-image">
        <%= image_tag 'frontend/login-bg/bg-8.jpg' %>
      </div>
      <div class="news-caption">
        <h4 class="caption-title"><i class="fa fa-edit text-success"></i> Signup Now</h4>
        <p>
          Signup now and be one of the first 100 users to have free premium access to our services. We will notify as soon as we are up.
        </p>
      </div>
    </div>
    <!-- end news-feed -->
    <!-- begin right-content -->
    <div class="right-content">
      <div class="m-b-20 relative m-l-20 m-t-20">
        <%= image_tag 'frontend/sitelogo.png', class: 'loginlogo' %>
        <strong class="absolute left-65 bottom--5">Get hired fast.</strong>
      </div>
      <!-- begin register-header -->
      <h1 class="register-header p-t-10">
        Sign Up
        <small>Create your Color Admin Account. It’s free and always will be.</small>
      </h1>
      <!-- end register-header -->
      <!-- begin register-content -->
      <div class="register-content">
        <form class="margin-bottom-0" name="signupForm" ng-submit="signup()" novalidate>
          <label class="control-label">Email</label>
          <div class="row m-b-15">
            <div class="col-md-12">
              <input type="text" class="form-control" name="email" placeholder="Email address" ng-model="userForm.email" ng-pattern="email_format" />
              <span class="error parsley-errors-list filled" ng-show="signupForm.email.$error.pattern">Invalid email</span>
            </div>
          </div>
          <label class="control-label">Password</label>
          <div class="row m-b-15">
            <div class="col-md-12">
              <input type="password" class="form-control" placeholder="Password" name="password" ng-model="userForm.password" ng-minlength="6" type="password" required />
              <span class="error parsley-errors-list filled" ng-show="signupForm.password.$error.minlength">password should be minimum of 6 characters</span>
            </div>
          </div>
          <label class="control-label">Confirm Password</label>
          <div class="row m-b-15">
            <div class="col-md-12">
              <input type="password" class="form-control" placeholder="Password" name="password_confirmation" ng-model="userForm.password_confirmation" ng-minlength="6" ng-pattern="userForm.password" required />
              <span class="error parsley-errors-list filled" ng-show="signupForm.password_confirmation.$error.pattern">password do not match</span>
            </div>
          </div>


          <div class="checkbox m-b-30">
            <label>
              <input type="checkbox" name="accept" ng-model="agreement_accepted" required /> By clicking Sign Up, you agree to our <a href="#">Terms</a> and that you have
              read our <a href="#">Data Policy</a>, including our <a href="#">Cookie Use</a>.
            </label>
          </div>
          <div class="register-buttons">
            <button type="submit" class="btn btn-primary btn-block btn-lg" ng-disabled="signupForm.$invalid && signupForm.$dirty">Sign Up</button>
          </div>
          <div class="m-t-20 m-b-40 p-b-40">
            Already a member? Click <%= link_to 'here', login_path %> to login.
          </div>
          <hr/>
          <p class="text-center text-inverse">
            &copy; Imprezify All Rights Reserved 2017
          </p>
        </form>
      </div>
      <!-- end register-content -->
    </div>
    <!-- end right-content -->
  </div>
  <!-- end register -->s
</div>
<!-- end page container -->
<script>var BASE_API_URL = '<%= BASE_API_URL %>'</script>
<%= javascript_include_tag 'auth' %>
<!--[if lt IE 9]>
<%= javascript_include_tag 'crossbrowser' %>
<![endif]-->

<script>
  AFTER_SIGNUP = '<%= IS_UP ? login_path : root_path %>'
  $(document).ready(function () {
    App.init();
  });
</script>

<script>
    (function() {
        var interakt = document.createElement('script');
        interakt.type = 'text/javascript'; interakt.async = true;
        interakt.src = "//cdn.interakt.co/interakt/dd31c5ebd6b6f9fb20ad18b9777dd460.js";
        var scrpt = document.getElementsByTagName('script')[0];
        scrpt.parentNode.insertBefore(interakt, scrpt);
    })()
</script>
</body>
</html>